project_id = "ckrevqokahrjsavfxhay"

[functions.create-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-cancellation-confirmation]
verify_jwt = false

[functions.get-receipt-url]
verify_jwt = false